"""
app/schemas.py
Pydantic request / response models for the ByteWallet AI API.
"""
from __future__ import annotations
from datetime import datetime
from typing import List, Optional, Dict
from pydantic import BaseModel, Field


#  Request model  #

class Transaction(BaseModel):
    timestamp: datetime
    amount: float = Field(..., gt=0, description="Positive amount in local currency")
    category: str
    type: str = Field(..., description="'expense' | 'income' | 'transfer'")
    note: Optional[str] = None
    payment_method: Optional[str] = None
    # Phase 3: Hyper-granular enrichment fields (all optional — backward compatible)
    merchant_name: Optional[str] = Field(None, description="Normalised merchant name, e.g. 'Highland Coffee'")
    latitude: Optional[float] = Field(None, description="Transaction location latitude")
    longitude: Optional[float] = Field(None, description="Transaction location longitude")


class EssentialObligation(BaseModel):
    name: str
    due_date: str          # e.g. "2026-03-30"
    amount: float


class Balances(BaseModel):
    banking: float = 0.0
    cash: float = 0.0


class MonthlyBudget(BaseModel):
    total: float
    by_category: Optional[Dict[str, float]] = None


class PredictBurnRateRequest(BaseModel):
    user_id: str
    nickname: Optional[str] = None
    currency: str = "VND"
    current_date: str = Field(..., description="ISO date string, e.g. '2026-03-15'")
    ai_mode: str = Field(default="auto", description="'auto' | 'local_only' | 'rules_only'")
    balances: Balances
    monthly_budget: MonthlyBudget
    essential_obligations: List[EssentialObligation] = []
    transactions: List[Transaction] = Field(..., description="At least current-month transactions; more = better")
    
    # New Alignment Schemas (Logic 1 & 2) from frontend
    user_context: Optional[UserContext] = None
    logic_signals: Optional[LogicSignals] = None
    recommendation_engine: Optional[RecommendationEngine] = None


#  Response model  #

class RiskyCategory(BaseModel):
    category: str
    current_spent: float
    avg_spent_last_3_months: float
    projected_spent: float


class TriggerRuleFlags(BaseModel):
    day_fraction: float
    budget_used_percent: float
    hit_15th_65_percent_rule: bool


#  New Alignment Schemas (Logic 1 & 2)  #

class UserContext(BaseModel):
    total_balance: float
    essential_expenses: float
    discretionary_baseline: float


class LogicSignals(BaseModel):
    shortfall_detected: bool
    shortfall_amount: float
    mid_month_alert: bool
    usage_percentage: float


class RecommendationEngine(BaseModel):
    target_category: str
    avg_cost_per_instance: float
    required_avoidance_count: int


class PredictBurnRateResponse(BaseModel):
    user_id: str
    currency: str
    risk_level: str                       # "low" | "medium" | "high"
    shortfall_prob: float
    predicted_month_end_balance: float
    predicted_total_spend: float
    budget_total: float
    budget_overshoot_amount: float
    budget_overshoot_percent: float
    
    # New Structured Alignment Fields
    user_context: Optional[UserContext] = None
    logic_signals: Optional[LogicSignals] = None
    recommendation_engine: Optional[RecommendationEngine] = None

    trigger_rule: Optional[str]           # "15th_65_percent" or None
    trigger_rule_flags: TriggerRuleFlags
    top_risky_categories: List[RiskyCategory]
    ai_message: str
    ai_mode_used: str                     # "rules_only", "ollama"
    proactive_alerts: List[ProactiveAlert] = []  # Phase 4: agent-generated alerts
    generated_at: datetime


#  Phase 4: Alert model  #

class ProactiveAlert(BaseModel):
    """An alert generated by one of the proactive monitoring agents."""
    agent: str
    type: str                  # "anomaly" | "subscription" | "savings"
    severity: str              # "info" | "warning" | "critical"
    title: str
    message: str
    suggested_action: str = ""
    metadata: Dict = {}

# Update forward ref
PredictBurnRateResponse.model_rebuild()
PredictBurnRateRequest.model_rebuild()


#  Phase 1: Chat models  #

class ChatRequest(BaseModel):
    """
    Natural-language financial question with a full wallet snapshot for context.
    The snapshot mirrors PredictBurnRateRequest so the LLM tools can access live data.
    """
    user_id: str
    question: str = Field(..., description="Free-form natural-language question, e.g. 'Can I afford a trip?'")
    # Wallet context — mirrors PredictBurnRateRequest fields
    currency: str = "VND"
    current_date: str = Field(..., description="ISO date string, e.g. '2026-03-15'")
    balances: Balances
    monthly_budget: MonthlyBudget
    essential_obligations: List[EssentialObligation] = []
    transactions: List[Transaction] = Field(default=[], description="Current month transactions")
    nickname: Optional[str] = None


class ChatResponse(BaseModel):
    user_id: str
    question: str
    answer: str                            # Plain-language LLM-generated answer
    tools_used: List[str] = []            # Which wallet tools the LLM invoked
    fallback_mode: bool = False           # True if Gemini was unavailable
    generated_at: datetime
