"""
app/agents/base_agent.py

Phase 4: Base class for all proactive monitoring agents.
Each agent inspects the user's wallet snapshot and returns a list of Alerts.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from abc import ABC, abstractmethod
from typing import List


@dataclass
class Alert:
    """Represents a proactive insight or warning generated by an agent."""
    agent: str                          # Source agent name
    type: str                          # "anomaly" | "subscription" | "savings" | "info"
    severity: str                      # "info" | "warning" | "critical"
    title: str                         # Short headline
    message: str                       # Full actionable message
    suggested_action: str = ""         # What the user should do
    metadata: dict = field(default_factory=dict)  # Extra data for UI rendering


class BaseAgent(ABC):
    """Abstract base for all ByteWallet monitoring agents."""

    name: str = "base"

    @abstractmethod
    def run(self, user_id: str, snapshot: dict) -> List[Alert]:
        """
        Inspect the snapshot and return a list of Alerts.
        Should never raise — catch exceptions internally.
        """
        ...
